language: python
dist: xenial
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
install: pip install tox-travis poetry
script: tox
jobs:
  include:
    - stage: coverage report
      python: 3.6
      install: pip install poetry coveralls
      script:
        - poetry install -E jwt -E fernet
        - poetry run pytest -v tests/
        - coveralls
